### ISSUE TITLE
User with username having email id is failing

### ISSUE THREAD

**Issue by vnbang2003** [pythonindia/wye#181]
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 87, in get_exception_response
    response = callback(request, **param_dict)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/utils/decorators.py", line 110, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/views/defaults.py", line 22, in page_not_found
    body = template.render(context, request)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 209, in render
    return self._render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 201, in _render
    return self.nodelist.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 903, in render
    bit = self.render_node(node, context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/base.py", line 917, in render_node
    return node.render(context)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 507, in render
    six.reraise(*exc_info)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 493, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 578, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/opt/envs/wye/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 495, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'profile-page' with arguments '()' and keyword arguments '{u'slug': u'vnbang2003@gmail.com'}' not found. 1 pattern(s) tried: [u'profile/(?P<slug>[a-zA-Z0-9]+)/$']

**Comment by vnbang2003** [comment]
@staranjeet Can you look in to this ? You can try on beta version which is live : http://beta.pythonexpress.in/

**Comment by staranjeet** [comment]
in this case, slug is your email id. Right?

**Comment by staranjeet** [comment]
In that case, we need to update the regex in the urls as
`    url(r'^(?P<slug>[a-zA-Z0-9@.]+)/$',
        views.ProfileView.as_view(), name='profile-page'),
    url(r'^(?P<slug>[a-zA-Z0-9@.]+)/edit$',
        views.ProfileEditView.as_view(), name='profile-edit')
`

**Comment by vnbang2003** [comment]
Looks like that should fix it . Can you send pul request for it.

**Comment by staranjeet** [comment]
PR #190
