### ISSUE TITLE
sample_data management command failing.

### ISSUE THREAD

**Issue by harisibrahimkv** [pythonindia/wye#290]
`python manage.py sample_data` fails with the following traceback:

```
(wye) ➜  wye git:(master) ✗ python manage.py sample_data
System check identified some issues:

WARNINGS:
profiles.Profile.usertype: (fields.W340) null has no effect on ManyToManyField.
  Updating domain to localhost:8000
  Creating Superuser
Traceback (most recent call last):
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/query.py", line 405, in get_or_create
    return self.get(**lookup), False
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
django.contrib.auth.models.DoesNotExist: User matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/local/Cellar/python3/3.5.2/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/Users/haris/contributions/wye/wye/base/management/commands/sample_data.py", line 43, in handle
    first_name='Admin')
  File "/Users/haris/contributions/wye/wye/base/management/commands/sample_data.py", line 88, in create_user
    user, created = get_user_model().objects.get_or_create(**params)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/query.py", line 407, in get_or_create
    return self._create_object_from_params(lookup, params)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/query.py", line 439, in _create_object_from_params
    obj = self.create(**params)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/query.py", line 348, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/base.py", line 734, in save
    force_update=force_update, update_fields=update_fields)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/base.py", line 771, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 189, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/haris/contributions/wye/wye/profiles/models.py", line 176, in create_user_profile
    profile.usertype.add(UserType.objects.get(slug='tutor'))
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/haris/.virtualenvs/wye/lib/python3.5/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
wye.profiles.models.DoesNotExist: UserType matching query does not exist.
```

**Comment by vnbang2003** [comment]
I think this is because of our plan to make each user by default as tutor.
 Fix for it us by add new user type as 'tutor' as first statement.

**Comment by vnbang2003** [comment]
Fixed the issue: https://github.com/pythonindia/wye/commit/cc006d5354e7f5794cd14e739b53f57290770936
